# Generated by Django 6.0.5 on 2026-05-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_reminder_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='due_date',
        ),
    ]
