# Generated by Django 6.0.5 on 2026-05-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_remove_reminder_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_fired',
            field=models.BooleanField(default=False),
        ),
    ]
