# Generated by Django 6.0.5 on 2026-06-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_reminder_is_fired'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='original_text',
            field=models.TextField(blank=True),
        ),
    ]
